apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: service-1
spec:
  selector:                                               # 2
    matchLabels:
      service1: v1.0                               
      service2: v1.0 
  replicas: 1                                             # 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 4
    rollingUpdate: 
      maxUnavailable: 0                                   # 5
      maxSurge: 1                                         # 6
  template:                                               # 7
    metadata:
      labels:
        app: dmausa/service2:v1.0                                 # 8
    spec:
      containers:
        - image: rinormaloku/sentiment-analysis-frontend
          imagePullPolicy: Always                         # 9
          name: sa-frontend
          ports:
            - containerPort: 80